name: Build specified projects
run-name: ${{ inputs.header }}
on:
  workflow_dispatch:
    inputs:
      header:
        description: "Display name of this run"
        required: true
        default: ""
      projects:
        description: "Colon-separated projects list"
        required: true
        default: ""
jobs:
  setup:
    runs-on: windows-latest
    outputs:
      projects: ${{ steps.variables.outputs.projects }}
      timestamp: ${{ steps.variables.outputs.timestamp }}
      output: ${{ steps.variables.outputs.output }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Set Variables
        id: variables
        shell: pwsh
        run: |
          $Projects = "${{ inputs.projects }}"
          If ($Projects -eq "<ALL>") { $Projects = (Get-ChildItem -Directory | Where-Object { Test-Path "$PSItem/xmake.lua" }).Name -Join ":" }
          $Projects = $Projects.Split(":") | Where-Object { Test-Path $PSItem } | ConvertTo-Json -Compress
          If ($Projects.Length -eq 0) { Write-Host "No projects to build" ; Exit 1 }
          If ($Projects.Substring(0, 1) -ne "[") { $Projects = "[$Projects]" }
          $Timestamp = Get-Date -UFormat "%s"
          echo "projects=$Projects" >> $Env:GITHUB_OUTPUT
          echo "timestamp=$Timestamp" >> $Env:GITHUB_OUTPUT
          echo "output=OutputDirectory" >> $Env:GITHUB_OUTPUT
  build:
    needs: setup
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.setup.outputs.projects) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install XMake
        uses: xmake-io/github-action-setup-xmake@master
      - name: Setup CommonLib
        shell: pwsh
        run: |
          git submodule add -b main https://github.com/libxse/commonlibsf.git lib/commonlibsf
          git submodule update --init --remote --recursive
          New-Item -ItemType Directory -Path "${{ matrix.project }}/lib"
          New-Item -ItemType Junction -Path "${{ matrix.project }}/lib/commonlibsf" -Value (Get-Item "lib/commonlibsf").FullName
      - name: Build Project
        shell: pwsh
        run: |
          Write-Host "Build project ${{ matrix.project }}"
          Push-Location ${{ matrix.project }}
          xmake build --yes
          Pop-Location
      - name: Upload Temp
        uses: actions/upload-artifact@main
        with:
          name: ${{ needs.setup.outputs.timestamp }}-${{ matrix.project }}
          path: |
            ${{ matrix.project }}/**/${{ matrix.project }}.dll
            ${{ matrix.project }}/**/${{ matrix.project }}.pdb
  collect:
    if: always()
    needs: [setup, build]
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Download Temp
        uses: actions/download-artifact@main
        with:
          path: ${{ needs.setup.outputs.output }}
          merge-multiple: true
      - name: Delete Temp
        shell: pwsh
        run: |
          $Env:GH_TOKEN = "${{ github.token }}"
          $Repo = "${{ github.repository }}"
          $RunID = "${{ github.run_id }}"
          $Response = gh api repos/$Repo/actions/runs/$RunID/artifacts | ConvertFrom-Json
          $Response.artifacts | Where-Object { $PSItem.name -match "${{ needs.setup.outputs.timestamp }}-(.+)" } | ForEach-Object {
              Write-Host "Delete artifact $($PSItem.name)"
              gh api repos/$Repo/actions/artifacts/$($PSItem.ID) -X DELETE
          }
      - name: Hash Artifacts
        shell: pwsh
        run: |
          $Root = "${{ needs.setup.outputs.output }}"
          $HashList = [System.Collections.ArrayList]::New() ; [Void]$HashList.Add("``````")
          Get-ChildItem $Root -File -Recurse | ForEach-Object { Move-Item $PSItem -Destination $Root }
          Get-ChildItem $Root -Directory | ForEach-Object { Remove-Item $PSItem -Recurse }
          Get-ChildItem $Root -File -Recurse | ForEach-Object {
            $Hash = Get-FileHash $PSItem -Algorithm SHA256
            $HashInfo = "$($Hash.Hash) = $($PSItem.Name)"
            [Void]$HashList.Add($HashInfo)
            Write-Host $HashInfo
          }
          [Void]$HashList.Add("``````")
          $HashList | Out-File "SHA256.md" -Encoding UTF8
          Compress-Archive "$Root/*" "build-${{ needs.setup.outputs.timestamp }}.zip"
      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-${{ needs.setup.outputs.timestamp }}
          path: ${{ needs.setup.outputs.output }}
      - name: Make Release
        uses: ncipollo/release-action@main
        with:
          artifacts: "build-${{ needs.setup.outputs.timestamp }}.zip"
          tag: ${{ needs.setup.outputs.timestamp }}
          name: ${{ inputs.header }}
          bodyFile: "SHA256.md"
