name: Build specified projects
run-name: ${{ inputs.header }}
on:
  workflow_dispatch:
    inputs:
      header:
        description: "Display name of this run"
        required: true
        default: ""
      projects:
        description: "Colon-separated projects list"
        required: true
        default: ""
jobs:
  setup:
    runs-on: windows-latest
    outputs:
      projects: ${{ steps.variables_id.outputs.projects }}
      timestamp: ${{ steps.variables_id.outputs.timestamp }}
      output: ${{ steps.variables_id.outputs.output }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Set Variables
        id: variables_id
        shell: pwsh
        run: |
          $Projects = "${{ inputs.projects }}"
          If ($Projects -eq "<ALL>") { $Projects = (Get-ChildItem -Directory | Where-Object { Test-Path "$PSItem/xmake.lua" }).Name -Join ":" }
          $Projects = $Projects.Split(":") | Where-Object { Test-Path $PSItem } | ConvertTo-Json -Compress
          If ($Projects.Length -eq 0) { Write-Host "No projects to build" ; Exit 1 }
          $Timestamp = Get-Date -UFormat "%s"
          echo "projects=$Projects" >> $Env:GITHUB_OUTPUT
          echo "timestamp=$Timestamp" >> $Env:GITHUB_OUTPUT
          echo "output=OutputDirectory" >> $Env:GITHUB_OUTPUT
  build:
    needs: setup
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.setup.outputs.projects) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install XMake
        uses: xmake-io/github-action-setup-xmake@master
      - name: Setup CommonLib
        shell: pwsh
        run: |
          git submodule add -b main https://github.com/libxse/commonlibsf.git lib/commonlibsf
          git submodule update --init --remote --recursive
          New-Item -ItemType Directory -Path "${{ matrix.project }}/lib"
          New-Item -ItemType Junction -Path "${{ matrix.project }}/lib/commonlibsf" -Value (Get-Item "lib/commonlibsf").FullName
      - name: Build Project
        shell: pwsh
        run: |
          Write-Host "Build project ${{ matrix.project }}"
          Push-Location ${{ matrix.project }}
          xmake build --yes
          Pop-Location
      - name: Upload Temp
        uses: actions/upload-artifact@main
        with:
          name: ${{ needs.setup.outputs.timestamp }}-${{ matrix.project }}
          path: |
            ${{ matrix.project }}/**/${{ matrix.project }}.dll
            ${{ matrix.project }}/**/${{ matrix.project }}.pdb
  collect:
    needs: [setup, build]
    if: always()
    runs-on: windows-latest
    steps:
      - name: Download Temp
        uses: actions/download-artifact@main
        with:
          pattern: ${{ needs.setup.outputs.timestamp }}-*
          path: ${{ needs.setup.outputs.output }}
          merge-multiple: true
      - name: Delete Temp
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $Pattern = "${{ needs.setup.outputs.timestamp }}-(.+)"
          $Repo = "${{ github.repository }}"
          $RunID = "${{ github.run_id }}"
          $Response = gh api Repos/$Repo/Actions/Runs/$RunID/Artifacts | ConvertFrom-Json
          $Response.Artifacts | Where-Object { $PSItem.Name -match $Pattern } | ForEach-Object {
              Write-Host "Delete artifact $($PSItem.Name)"
              gh api Repos/$Repo/Actions/Artifacts/$($PSItem.ID) -X DELETE
          }
      - name: Collect Artifacts
        shell: pwsh
        run: |
          Get-ChildItem ${{ needs.setup.outputs.output }} -File -Recurse | ForEach-Object {
            $Hash = Get-FileHash $PSItem -Algorithm SHA256
            Write-Host "$($Hash.Hash) = $($Hash.Path)"
          }
      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-${{ needs.setup.outputs.timestamp }}
          path: ${{ needs.setup.outputs.output }}
